"""Traders table names changed

Revision ID: 0d8b19ea0564
Revises: 27777b672981
Create Date: 2020-11-06 14:20:49.770810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8b19ea0564'
down_revision = '27777b672981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traders', sa.Column('crypto_address', sa.String(length=128), nullable=True))
    op.add_column('traders', sa.Column('trader_id', sa.String(length=128), nullable=True))
    op.add_column('traders', sa.Column('user_regtime', sa.Float(), nullable=True))
    op.create_index(op.f('ix_traders_crypto_address'), 'traders', ['crypto_address'], unique=True)
    op.create_index(op.f('ix_traders_trader_id'), 'traders', ['trader_id'], unique=True)
    op.drop_index('ix_traders_cryptoAddress', table_name='traders')
    op.drop_index('ix_traders_traderID', table_name='traders')
    op.drop_column('traders', 'cryptoAddress')
    op.drop_column('traders', 'userRegTime')
    op.drop_column('traders', 'traderID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traders', sa.Column('traderID', sa.VARCHAR(length=128), nullable=True))
    op.add_column('traders', sa.Column('userRegTime', sa.FLOAT(), nullable=True))
    op.add_column('traders', sa.Column('cryptoAddress', sa.VARCHAR(length=128), nullable=True))
    op.create_index('ix_traders_traderID', 'traders', ['traderID'], unique=1)
    op.create_index('ix_traders_cryptoAddress', 'traders', ['cryptoAddress'], unique=1)
    op.drop_index(op.f('ix_traders_trader_id'), table_name='traders')
    op.drop_index(op.f('ix_traders_crypto_address'), table_name='traders')
    op.drop_column('traders', 'user_regtime')
    op.drop_column('traders', 'trader_id')
    op.drop_column('traders', 'crypto_address')
    # ### end Alembic commands ###
