"""empty message

Revision ID: 27777b672981
Revises: fd7360818985
Create Date: 2020-10-16 18:50:18.628700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27777b672981'
down_revision = 'fd7360818985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('strategyID', sa.Integer(), nullable=True),
    sa.Column('algoOpenness', sa.Float(), nullable=True),
    sa.Column('maxCapCapacity', sa.Float(), nullable=True),
    sa.Column('winRate', sa.Float(), nullable=True),
    sa.Column('profitability', sa.Float(), nullable=True),
    sa.Column('marketBeat', sa.Float(), nullable=True),
    sa.Column('resultRate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_strategyID'), 'rating', ['strategyID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_strategyID'), table_name='rating')
    op.drop_table('rating')
    # ### end Alembic commands ###
