"""empty message

Revision ID: 6a0c9f22682e
Revises: 
Create Date: 2020-10-16 13:10:53.502381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0c9f22682e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategyID', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('startDayBalance', sa.Float(), nullable=True),
    sa.Column('onMargin', sa.Float(), nullable=True),
    sa.Column('comissions', sa.Float(), nullable=True),
    sa.Column('endDayBalance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_strategyID'), 'accounts', ['strategyID'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('strategyID', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('orderID', sa.String(length=128), nullable=True),
    sa.Column('direction', sa.String(length=64), nullable=True),
    sa.Column('orderType', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('timeInForce', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('attribute', sa.String(length=64), nullable=True),
    sa.Column('positionID', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_orderID'), 'orders', ['orderID'], unique=False)
    op.create_index(op.f('ix_orders_strategyID'), 'orders', ['strategyID'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('strategyID', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=64), nullable=True),
    sa.Column('openPrice', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('liqPrice', sa.Float(), nullable=True),
    sa.Column('urealisedPL', sa.Float(), nullable=True),
    sa.Column('realisedPL', sa.Float(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('positionID', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_positionID'), 'positions', ['positionID'], unique=False)
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_strategyID'), 'positions', ['strategyID'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategyID', sa.Integer(), nullable=True),
    sa.Column('regTime', sa.Float(), nullable=True),
    sa.Column('ush', sa.String(length=128), nullable=True),
    sa.Column('strategyName', sa.String(length=128), nullable=True),
    sa.Column('algoOpenness', sa.Integer(), nullable=True),
    sa.Column('capitalCapacity', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_strategyID'), 'strategies', ['strategyID'], unique=True)
    op.create_index(op.f('ix_strategies_ush'), 'strategies', ['ush'], unique=True)
    op.create_table('strategies_i_ds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('salt', sa.LargeBinary(), nullable=True),
    sa.Column('hashKey', sa.LargeBinary(), nullable=True),
    sa.Column('traderID', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_i_ds_traderID'), 'strategies_i_ds', ['traderID'], unique=False)
    op.create_table('traders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traderID', sa.String(length=128), nullable=True),
    sa.Column('userRegTime', sa.Float(), nullable=True),
    sa.Column('cryptoAddress', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traders_cryptoAddress'), 'traders', ['cryptoAddress'], unique=True)
    op.create_index(op.f('ix_traders_traderID'), 'traders', ['traderID'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traders_traderID'), table_name='traders')
    op.drop_index(op.f('ix_traders_cryptoAddress'), table_name='traders')
    op.drop_table('traders')
    op.drop_index(op.f('ix_strategies_i_ds_traderID'), table_name='strategies_i_ds')
    op.drop_table('strategies_i_ds')
    op.drop_index(op.f('ix_strategies_ush'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_strategyID'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_positions_strategyID'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_index(op.f('ix_positions_positionID'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_strategyID'), table_name='orders')
    op.drop_index(op.f('ix_orders_orderID'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_accounts_strategyID'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
