"""empty message

Revision ID: fd7360818985
Revises: 6a0c9f22682e
Create Date: 2020-10-16 17:10:26.887093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7360818985'
down_revision = '6a0c9f22682e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strategies_ush', table_name='strategies')
    op.create_index(op.f('ix_strategies_ush'), 'strategies', ['ush'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategies_ush'), table_name='strategies')
    op.create_index('ix_strategies_ush', 'strategies', ['ush'], unique=1)
    # ### end Alembic commands ###
